apiVersion: monitor.gatus-operator.dev/v1
kind: GatusCheck
metadata:
  labels:
    app.kubernetes.io/name: gatus-operator
    app.kubernetes.io/managed-by: kustomize
  name: gatuscheck-sample
spec:
  # TODO(user): Add fields here
